# Generated by Django 6.0.2 on 2026-02-12 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.CharField(default=django.utils.timezone.now),
        ),
    ]
