# Generated by Django 6.0.2 on 2026-02-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0002_post_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
