# Generated by Django 6.0.2 on 2026-02-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0003_remove_post_likes_post_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ForeignKey(
                default=[], on_delete=django.db.models.deletion.CASCADE, to="Main.like"
            ),
        ),
    ]
