# Generated by Django 6.0.2 on 2026-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0004_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
