# Generated by Django 6.0.2 on 2026-02-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0005_alter_post_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
