# Generated by Django 6.0.2 on 2026-02-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0006_remove_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user_id",
        ),
        migrations.AddField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
