# Generated by Django 6.0.2 on 2026-02-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0007_remove_post_created_at_remove_post_post_content_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
