# Generated by Django 6.0.2 on 2026-02-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0008_delete_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
