# Generated by Django 6.0.2 on 2026-02-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0010_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postContent", models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
