# Generated by Django 6.0.2 on 2026-02-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0011_post_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
