# Generated by Django 6.0.2 on 2026-02-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="username",
            field=models.CharField(default="anonymous"),
        ),
    ]
