# Generated by Django 6.0.2 on 2026-02-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="follower_id",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="user_id",
        ),
        migrations.AddField(
            model_name="follow",
            name="follower",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="follow",
            name="username",
            field=models.CharField(default=""),
        ),
    ]
